require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - shared_examples_for
  Exclude:
    - Guardfile

# Seems to be breaking tests when recommended fixes for this cop are applied
Rails/HttpPositionalArguments:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/MixinUsage:
  Exclude:
    - bin/*

Style/FrozenStringLiteralComment:
  Enabled: false
